# Db
development:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('pg_url', 'postgres://localhost') %>
  database: dcaf_case_management_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('pg_url', 'postgres://localhost') %>
  database: dcaf_case_management_test
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

staging:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>
    pool: 10
  cable:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    pool: 5
    schema_dump: cable_schema.rb
