#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Db
development:
  <<: *default
  url: <%= ENV.fetch('pg_url', 'postgres://localhost') %>
  database: dcaf_case_management_development
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  url: <%= ENV.fetch('pg_url', 'postgres://localhost') %>
  database: dcaf_case_management_test
  username: <%= ENV['POSTGRES_USER'] || `whoami` %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    pool: 10
  cache:
    <<: *primary_production
    database: daria_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: daria_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: daria_production_cable
    migrations_paths: db/cable_migrate
