default: &all
  funds:
    - "Baltimore Abortion Fund"
    - "Richmond Reproductive Freedom Project (RRFP)"
    - "Blue Ridge Abortion Assistance Fund (BRAAF)"
    - "Tiller Fund (NNAF)"
    - "Carolina Abortion Fund" 
    - "Women's Medical Fund (Philadelphia)"
    - "NYAAF (New York)"
    - "Clinic discount"
    - "Other funds (see notes)"
    
development:
  <<: *all

test:
  <<: *all

production:
  <<: *all